spring:
  boot:
    admin:
      client:
        url: http://localhost:7030
        username: root
        password: 123456
        instance:
          prefer-ip: true
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7000/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      instance-id: ${spring.application.name}:${random.value}
jobs:
  admin-address: http://127.0.0.1:7040
  app-name: job-executor
  app-port: 9999